---
functional:
- Пользователь должен иметь возможность зарегистрироваться с указанием электронной почты или через свой аккаунт Github или Discord
- Пользователь должен иметь возможность создать свою игру или присоединиться к игре другого игрока
- Пользователю должен быть доступен выбор уровня сложности игры (от 1 до 4), длительности игры (от 3 до 60 минут), темы и языка программирования
- Пользователь должен иметь возможность сменить выбранный язык программирования и отредактировать информацию о себе в своём профиле
- Пользователь может играть с другом, случайным соперником или ботом
- У пользователя должен быть личный кабинет, где доступна статистика сыгранных игр, рейтинг, календарь активности
- Во время игры пользователь должен видеть два редактора кода — свой и соперника, изменения в редакторах должны отображаться в реальном времени у обоих игроков
- Во время игры пользователю должен быть доступен чат с соперником
- Пользователь должен иметь возможность сдаться в игре, нажав соответсвующую кнопку
- На главной странице сайта после входа пользователю должен быть доступен общий чат всех пользователей
- Пользователь должен иметь возможность посмотреть чужую игру 
- Пользователь должен иметь возможность неограниченное количество раз проверить своё решение во время игры специальной кнопкой Check
- Пользователь должен иметь возможность продолжить игру, если у соперника прервалось соединение, и вернуться в начатую игру, если соединение прервалось у него самого
- Когда один из игроков нашёл правильный ответ, у обоих игроков должно появиться модальное окно, где написано, кто является победителем этой игры
- После победы у пользователя-победителя должна появиться кнопка, которая позволит выйти из игры
- У пользователя-проигравшего должна быть возможность пройти игру до конца и найти верное решение, после того, как его соперник-победитель вышел
- Игра должна считаться законченной и удаляться из памяти после того, как её покинули два игрока
- Пользователь должен иметь возможность создать турнир или присоединиться к турниру, созданному другим игроком
- Пользователь должен иметь возможность смотреть рейтинговые таблицы
non-functional:
- Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен быть удобным на мобильном устройстве
- Сайт должен быть протестирован на совместимость с последними версиями браузеров
- Сайт должен быть способен обрабатывать большое количество трафика (1000 одновременных пользователей)
implicit:
- Сайт должен своевременно отображать у пользователя данные, которые его соперник печатает во время игры, даже при разной скорости соединения у игроков
- Пользователь должен оставаться авторизованным после перезагрузки страницы
